name: Check and Migrate Database

on:
  workflow_dispatch:  # Permite iniciar manualmente el workflow

jobs:
  check-database:
    runs-on: ubuntu-latest

    steps:
      - name: Check Database Status
        run: |
          if ! pg_isready -d ${{ secrets.DATABASE_URL }}; then
            echo "Database is down! Migrating..."
            npx prisma init
            npx prisma migrate deploy
            npx prisma db seed
          else
            echo "Database is up! No action needed."
          fi
